-- Insert old user data directly into PostgreSQL database
-- Run this inside the PostgreSQL container

-- Insert ameer_arsath user
INSERT INTO users (
    username,
    email,
    password_hash,
    encryption_salt,
    key_verification_payload,
    encryption_method,
    key_derivation_iterations,
    is_active,
    is_verified,
    must_change_password,
    role,
    mfa_enabled,
    mfa_secret,
    mfa_setup_date,
    mfa_last_used,
    backup_codes,
    backup_codes_generated_at,
    failed_login_attempts,
    locked_until,
    last_login,
    last_password_change,
    created_at,
    updated_at,
    created_by,
    full_name,
    department
) VALUES (
    'ameer_arsath',
    'ameerarsath2@gmail.com',
    '$2b$12$jDL6i2jLdDuUkOnb0KcdfORcDfrHQzo9hLV6H9PgvuNycB.U3FKim',
    'V6Vi46InLBidRtjm4Mx/C8+NUA4IR8k/rRFCrGlkaas=',
    '{"encrypted_dek": "vKJargXCKf7vzbMc3vnAjJclxk56waA=", "encryption_iv": "D8YHk2qbVhjmncK4", "encryption_auth_tag": "n4DYnUOvfRv6Ppfw3wGr+w=="}',
    'PBKDF2-SHA256',
    500000,
    true,
    true,
    false,
    'user',
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NULL,
    'ameer_arsath',
    NULL
);

-- Insert rahumana user
INSERT INTO users (
    username,
    email,
    password_hash,
    encryption_salt,
    key_verification_payload,
    encryption_method,
    key_derivation_iterations,
    is_active,
    is_verified,
    must_change_password,
    role,
    mfa_enabled,
    mfa_secret,
    mfa_setup_date,
    mfa_last_used,
    backup_codes,
    backup_codes_generated_at,
    failed_login_attempts,
    locked_until,
    last_login,
    last_password_change,
    created_at,
    updated_at,
    created_by,
    full_name,
    department
) VALUES (
    'rahumana',
    'rahumana@test.com',
    '$2b$12$bWINlzucx/7Pq7EO8pPiJufDZQsHSxDlbtvTVP7H.oKnaRC4mZNE6',
    'A4eSOJpzoRq/yynj+IaQTXHVmqKUklJqAb/9Yc/Qa90=',
    '{"encrypted_dek": "jcNMcK/dQQAz/fXOrNa1YuG5ylW/Y2x4rd4ljG6IzYb5Gu7KpXeCoxBxOXGhaYkrXGb8/w==", "encryption_iv": "7pCQjY104ZqvSYvG", "encryption_auth_tag": "PRvHaUSFbCYLBtvpdTKzSA=="}',
    'PBKDF2-SHA256',
    500000,
    true,
    true,
    false,
    'super_admin',
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NULL,
    'Test User',
    NULL
);

-- Insert suga user (note: key_verification_payload is incomplete in your data, so leaving it NULL)
INSERT INTO users (
    username,
    email,
    password_hash,
    encryption_salt,
    key_verification_payload,
    encryption_method,
    key_derivation_iterations,
    is_active,
    is_verified,
    must_change_password,
    role,
    mfa_enabled,
    mfa_secret,
    mfa_setup_date,
    mfa_last_used,
    backup_codes,
    backup_codes_generated_at,
    failed_login_attempts,
    locked_until,
    last_login,
    last_password_change,
    created_at,
    updated_at,
    created_by,
    full_name,
    department
) VALUES (
    'suga',
    'sugail@gmail.com',
    '$2b$12$gxs4PiVj5rHUzk.1z/5fPuVhPj44zkIM.e5T9iYvSz/JDwy3yjXm.',
    'I+Ybkxm+tECRroI67HN5N8tSfjzVYCdrw8fs/o9vvsc=',
    NULL,  -- Incomplete payload from your data
    'PBKDF2-SSHA256',
    500000,
    true,
    true,
    false,
    'user',
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NULL,
    NULL,
    NULL
);

-- Show all users to verify
SELECT id, username, email, role, is_active, created_at FROM users;